openapi: 3.0.1
info:
  title: Named entities recognition API
  description: API to detect named entities in a text.
  version: 0.2.0

servers:
- url: /

paths:
  /ner/{lang}:
    post:
      tags:
      - Speech-To-Text API
      summary: Perform Speech-to-Text
      parameters:
        - name: lang
          in: path
          required: true
          description: Language
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request'
      responses:
        200:
          description: "Job successfully finished"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responsemodel'
        400:
          description: "Bad request"
        500:
          description: "Server error"
        
components:
  schemas:
    article:
      type: object
      properties:
        text:
          type: string
          default: This is an article.
    request:
      type: object
      properties:
        articles:
          type: array
          required: true
          items:
            $ref: '#/components/schemas/article'
        component_cfg:
          type: object

    entity:
      type: object
      properties:
        text:
          type: string
        label:
          type: string
        start:
          type: integer
        end:
          type: integer
    batch:
      type: object
      properties:
        text:
          type: string
        ents:
          type: array
          items:
            $ref: '#/components/schemas/entity'
    
    responsemodel:
      type: object
      properties:
        ner:
          type: array
          items:
            $ref: '#/components/schemas/batch'
        